#!/bin/sh

installPath=/opt/mpluginv4

if [ -d $installPath ]; then
	chmod 777 $installPath -R
fi 

if [ -f /etc/udev/rules.d/90-lm-mtoken-plugin.rules ]; then
	chmod 777 /etc/udev/rules.d/90-lm-mtoken-plugin.rules
fi 

if [ -f /etc/xdg/autostart/mpluginv4.desktop ]; then
	chmod 777  /etc/xdg/autostart/mpluginv4.desktop 
fi

cd $installPath/script

./run.sh

#安装服务证书
DIR=$(pwd)

if [ -f $installPath/conf/server.pem ];then
	if [ "$( which certutil )" = "" ];then
		echo "插件服务安装成功。"
		echo "如果使用https访问设备，请手动将安装目录下的server.pem证书导入到火狐浏览器中。"
		echo "或者执行[ $installPath/preinstall ]目录下的脚本 install.sh导入证书。"
	else
		### For cert8 (legacy - DBM)
		for certDB in $(find /home -name "cert8.db")
		do
		    certdir=$(dirname ${certDB});
		    (certutil -A -n "mPluginCA" -t "TC,TC,TC" -i "$installPath/conf/server.pem" -d dbm:${certdir} &)
		done

		### For cert9 (SQL)
		for certDB in $(find /home -name "cert9.db")
		do
		    certdir=$(dirname ${certDB});
		    (certutil -A -n "mPluginCA" -t "TC,TC,TC" -i "$installPath/conf/server.pem" -d sql:${certdir} &)
		done
	fi
fi

