#!/bin/sh

#终止服务进程
if [ $(ps -ef|grep mPluginV4 |grep -v grep | wc -l) -gt 0 ]; then
		killall mPluginV4
fi 

#卸载服务证书
if [ "$( which certutil )" = "" ];then
	echo " "
else
	### For cert8 (legacy - DBM)
	for certDB in $(find /home -name "cert8.db")
	do
	    certdir=$(dirname ${certDB});
	    #certutil -D -n "mPluginCA" -d dbm:${certdir}
	done

	### For cert9 (SQL)
	for certDB in $(find /home -name "cert9.db")
	do
	    certdir=$(dirname ${certDB});
	    #certutil -D -n "mPluginCA" -d dbm:${certdir}
	done
fi


