#!/bin/sh

APPNAME=lm-gm3000user
GMLIB=libgm3000.1.0.so
RULE90NAME=90-lm-mtoken-user.rules

if [ -f /etc/udev/rules.d/$RULE90NAME ]; then
	rm /etc/udev/rules.d/$RULE90NAME
fi 

if [ -f /usr/lib64/$GMLIB ]; then
	rm /usr/lib64/$GMLIB
fi 

if [ -f /usr/lib/$GMLIB ]; then
	rm /usr/lib/$GMLIB
fi 


#删除桌面快捷图标
if [ -d /home ]; then
	for i in /home/*/Desktop/$APPNAME.desktop; do
		if [ -f $i ];then
			rm $i
		fi
	done
	unset i
fi

if [ -d /home ]; then
	for i in /home/*/桌面/$APPNAME.desktop; do
		if [ -f $i ];then
			rm $i
		fi
	done
	unset i
fi

#删除其它链接文件

if [ -f /etc/xdg/autostart/$APPNAME.desktop ];then
	rm /etc/xdg/autostart/$APPNAME.desktop
fi

#杀掉进程
pgrep GM3000User
if [ $? -eq 0 ];then
	pkill -9 GM3000User
fi

if [ -d /opt/lm-gm3000user ]; then
	rm -Rf /opt/lm-gm3000user
fi 

