#!/bin/sh

installPath=/opt/apps/com.longmai.mpluginv4/files

if [ -d $installPath ]; then
	chmod 777 $installPath -R
fi 

#将配置文件拷贝到系统目录下
#配置文件 "90-mtoken.rules" 用来给设备增加权限

if [ -f /etc/udev/rules.d/90-mtoken.rules ]; then
	chmod 777 /etc/udev/rules.d/90-mtoken.rules
else
	cp $installPath/conf/90-mtoken.rules /etc/udev/rules.d/90-mtoken.rules
	chmod 777 /etc/udev/rules.d/90-mtoken.rules
fi 

cd $installPath/script

#启动服务程序
./run.sh

#将服务证书导入到火狐浏览器中，用来支持https访问设备
DIR=$(pwd)

if [ -f $installPath/conf/server.pem ];then
	if [ "$( which certutil )" = "" ];then
		echo "插件服务安装成功。"
		echo "如果使用https访问设备，请手动将安装目录下的server.pem证书导入到火狐浏览器中。"
	else
		### For cert8 (legacy - DBM)
		for certDB in $(find /home -name "cert8.db")
		do
		    certdir=$(dirname ${certDB});
		    (certutil -A -n "mPluginCA" -t "TC,TC,TC" -i "$installPath/conf/server.pem" -d dbm:${certdir} &)
		done

		### For cert9 (SQL)
		for certDB in $(find /home -name "cert9.db")
		do
		    certdir=$(dirname ${certDB});
		    (certutil -A -n "mPluginCA" -t "TC,TC,TC" -i "$installPath/conf/server.pem" -d sql:${certdir} &)
		done
	fi
fi

